デザインの見直し / スマホ
enpitut2017/tourism_supporter pull request #104
Opened 2017-11-15 05:43 UTC by Mori-Atsushi

close #96

2017-11-15 05:45 UTC, ten1010 requested changes

2017-11-15 05:45 UTC, ten1010 commented on app/assets/stylesheets/application.scss
> +
改行が多い

2017-11-17 07:02 UTC, Shizuma5 approved these changes
良いと思います

2017-11-17 07:04 UTC, ten1010 approved these changes

2017-11-17 07:08 UTC, merged